language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-protractor' ]; then cd .. && eval "mv $currentfolder generator-protractor" && cd generator-protractor; fi

